name: 🐛 Bug Report
description: Report an error, crash, or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What went wrong?
      placeholder: Steps to reproduce the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Python/Node version, etc.
      placeholder: e.g. Windows 11, Python 3.13, Node 20
    validations:
      required: false
