blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/fjoelnr/minecraft-llm-agents/tree/dev/docs
    about: Please check the documentation before filing new issues.
