name: CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  python:
    name: Python Lint & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: orchestrator
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest black ruff

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (format check)
        run: black --check .

      - name: Pytest
        run: pytest tests -v

  node:
    name: Node Lint (gateway)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bot-gateway
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: bot-gateway/package-lock.json

      - name: Install
        run: npm ci || npm i

      - name: ESLint
        run: npm run lint
