name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # create release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: tag
        run: |
          REF="${GITHUB_REF#refs/tags/}"
          echo "version=${REF}" >> $GITHUB_OUTPUT

      - name: Prepare Python env (for changelog extraction)
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Extract release notes from CHANGELOG.md
        id: notes
        run: |
          python .github/scripts/extract_changelog.py "${{ steps.tag.outputs.version }}" > RELEASE_NOTES.md
          echo 'notes<<EOF' >> $GITHUB_OUTPUT
          cat RELEASE_NOTES.md >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Try building paper (optional)
        id: paper
        run: |
          if [ -f paper/neurips_2023.sty ] && [ -f paper/main.tex ]; then
            echo "Building paper/main.tex"
            sudo apt-get update && sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
            cd paper
            latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex
            cd ..
            echo "paper_built=true" >> $GITHUB_OUTPUT
          else
            echo "Paper style or main.tex missing; skipping build."
            echo "paper_built=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.version }}
          name: MCP-Craft ${{ steps.tag.outputs.version }}
          body: ${{ steps.notes.outputs.notes }}
          draft: false
          prerelease: false

      - name: Upload paper PDF (if built)
        if: steps.paper.outputs.paper_built == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            paper/main.pdf
